[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-u-beautiful-chat"
version = "2501220"
description = "Null"

[project.entry-points."endstone"]
u_beautiful_chat = "endstone_u_beautiful_chat:u_beautiful_chat"